version: "3.9"
services:
  jupyter:
    image: local/jupyter
    build: .
    volumes:
    - ./notebooks:/opt/notebooks
    ports: 
    - "${PORT}:${PORT}"
    #command: tail -F nothing
    
    #command: 
    #- "/opt/conda/bin/jupyter"
    #- "notebook"
    #- "--notebook-dir=/opt/notebooks"
    #- "--ip='*'"
    #- "--port=8888"
    #- "--no-browser",
    #- "--allow-root"
